### ISSUE TITLE
SIM-GH action to run e2e tests on PR open and approval

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-simulator#265]
Decide whether to run one action for the three platforms or one action per platform: [ubuntu.latest, macos.latest, windows.latest] 
The tests should be executed from the CLI

Example:
```
name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
```
